---
- name: Upload Config | Kibana
  template:
    src: config/kibana.yml
    dest: "/opt/kibana/kibana-{{ kibana_version }}-linux-x64/config/kibana.yml"
  tags:
    - configuration
    - template-configuration
    - kibana
